# Cria container Docker para utilizar o PostgreSQL para gerar o banco de dados

version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: todo-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: guerr
      POSTGRES_PASSWORD: akg030505
      POSTGRES_DB: todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
